Update disable2

diff --git a/disable2 b/disable2
--- a/disable2
+++ b/disable2
@@ -1,68 +1,43 @@
 #!/bin/bash
 
-# Check if IPset and IPtables-persistent are installed, if not install them
-if [[ $(command -v ipset) == "" ]]; then
-    echo "Installing IPset..."
-    if [[ $(command -v apt-get) != "" ]]; then
-        sudo apt-get update -y
-        sudo apt-get install -y ipset
-    elif [[ $(command -v yum) != "" ]]; then
-        sudo yum update -y 
-        sudo yum install -y ipset
+# Check if ipset is installed, if not, install it
+if ! command -v ipset &> /dev/null
+then
+    echo "ipset not found, installing..."
+    if [[ $(lsb_release -si) == "Ubuntu" ]]; then
+        sudo apt-get update
+        sudo apt-get install ipset -y
+    elif [[ $(lsb_release -si) == "CentOS" ]]; then
+        sudo yum install ipset -y
+    elif [[ $(lsb_release -si) == "Debian" ]]; then
+        sudo apt-get update
+        sudo apt-get install ipset -y
     else
-        echo "Could not find a package manager to install IPset. Aborting."
+        echo "Unsupported distribution."
         exit 1
     fi
 fi
 
-if [[ $(command -v iptables-persistent) == "" ]]; then
-    echo "Installing IPtables-persistent..."
-    if [[ $(command -v apt-get) != "" ]]; then
-        sudo apt-get update -y 
-        sudo apt-get install -y iptables-persistent
-    elif [[ $(command -v yum) != "" ]]; then
-        sudo yum update -y 
-        sudo yum install -y iptables-services
-    else
-        echo "Could not find a package manager to install IPtables-persistent. Aborting."
-        exit 1
-    fi
+# Check if iptables-services is installed, if not, install it
+if ! rpm -q iptables-services &> /dev/null
+then
+    echo "iptables-services not found, installing..."
+    sudo yum install iptables-services -y
 fi
 
-# Install IPset-china
-if [[ $(command -v ipset) != "" ]]; then
-    if [[ ! -f /usr/sbin/ipset-china ]]; then
-        echo "Installing IPset-china..."
-        wget https://github.com/koonlekom/ipset-china/archive/master.zip
-        unzip master.zip
-        cd ipset-china-master/
-        sudo ./install.sh
-    fi
-fi
+# Create an ipset called "china"
+sudo ipset create china hash:net
 
-# Configure IPset-china
-if [[ $(command -v ipset) != "" && -f /usr/sbin/ipset-china ]]; then
-    echo "Configuring IPset-china..."
-    sudo /usr/sbin/ipset-china-update -c /etc/ipset-china/ipv4.txt -6 /etc/ipset-china/ipv6.txt -s china -S chnroute -m 32 -M 64
-else
-    echo "IPset-china is not installed, skipping IPset-china configuration."
-fi
+# Download the latest APNIC delegated file
+wget https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest -O delegated-apnic-latest.txt
 
-# Configure IPtables rules
-echo "Configuring IPtables rules..."
-sudo iptables -A INPUT -p tcp --dport 40000:50000 -m set --match-set china dst -j ACCEPT
-sudo iptables -A INPUT -p tcp --dport 40000:50000 -j DROP
+# Add China's IP ranges to the "china" ipset
+cat delegated-apnic-latest.txt | grep '|CN|ipv4|' | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' | sudo xargs -I{} ipset add china {}
 
-# Save IPtables rules
-echo "Saving IPtables rules..."
-if [[ $(command -v iptables-save) != "" ]]; then
-    sudo iptables-save > /etc/iptables/rules.v4
-    sudo ip6tables-save > /etc/iptables/rules.v6
-elif [[ $(command -v netfilter-persistent) != "" ]]; then
-    sudo netfilter-persistent save
-else
-    echo "Could not find a suitable command to save IPtables rules. Aborting."
-    exit 1
-fi
+# Allow Chinese IP addresses to access ports 40000-50000, and deny others
+sudo iptables -I INPUT -m set ! --match-set china src -p tcp --dport 40000:50000 -j DROP
 
-echo "Done!"
+# Save the iptables rules
+sudo service iptables save
+
+echo "Done."
